spring.application.name=xmlparser
server.port=8081
xml.folder.path=C:\\Users\\Lenovo\\Desktop\\schemaExecution
parent.folder.path=C:\\Users\\Lenovo\\Desktop\\instance
file.folder.path=C:\\Users\\Lenovo\\Desktop\\mutex\\
openjms.start=C:\\Users\\Lenovo\\Desktop\\start-openjms.bat
openjms.stop=C:\\Users\\Lenovo\\Desktop\\stop-openjms.bat
