spring.application.name=xmlparser
server.port=8081
xml.folder.path=C:\\Users\\Lenovo\\Desktop\\schemaExecution
parent.folder.path=C:\\Users\\Lenovo\\Desktop\\instance
file.folder.path=C:\\Users\\Lenovo\\Desktop\\mutex
openjms.start=C:\\Users\\Lenovo\\Desktop\\Soutenance\\mon-projet\\xmlparser\\start-openjms-java8.bat
openjms.stop=C:\\Users\\Lenovo\\Desktop\\Soutenance\\mon-projet\\xmlparser\\stop-openjms-java8.bat
